### ISSUE TITLE
 omnitest(correctVal = 5)

### ISSUE THREAD

**Issue by bonzoyang** [wush978/StatMLDM#1]
發生在TM-RStatistics-01-EDA中，關卡52
"這裡複習一下seq函數。請問同學，seq(0,1,0.25)的長度會是多少？" 
雖然答案是5，但打seq(0,1,0.25)也會過，yaml的寫法是omnitest(correctVal = 5)
不知道是不是omnitest的bug

**Comment by wush978** [comment]
是的，你有興趣發個PR嗎？XD
改成用val_is之類的helper test function

**Comment by bonzoyang** [comment]
sure，但這兩天在Trend Micro，我會找時間把PR補上（還有swirl()的），我動作不見得很及時，但會把這個弄完的 :D
